apiVersion: batch/v1
kind: Job
metadata:
  name: taskapp-db-init
  namespace: taskapp
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-init
          image: ghcr.io/voddy001/taskapp-backend:v0.1.0
          command: ["python", "init_db.py"]
          envFrom:
            - configMapRef:
                name: taskapp-config
            - secretRef:
                name: taskapp-secrets