apiVersion: batch/v1
kind: Job
metadata:
  name: taskapp-db-init
  namespace: taskapp
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: db-init
          image: ghcr.io/voddy001/taskapp-backend:v0.1.1
          command: ["python", "init_db.py"]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: taskapp-config
            - secretRef:
                name: taskapp-secrets