[control_plane]
control-plane ansible_host=44.202.207.122

[workers]
worker-1 ansible_host=44.205.19.0
worker-2 ansible_host=3.218.151.67

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/phoenix-cluster.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'